### ISSUE TITLE
Emotion or PostCSS

### ISSUE THREAD

**Issue by baron816** [SkinnyFatSumo/Visual-Portfolio-Platform#2]
https://postcss.org/
https://emotion.sh/docs/introduction

Using either would cut down on your CSS woes. You'd get modularized CSS, so you're not just working in a global namespace for your styles.

**Comment by SkinnyFatSumo** [comment]
I will definitely look into those. The CSS on this project got to be a huge pain, and if I decide to bring the site live it would definitely benefit from modularized CSS.
