### ISSUE TITLE
Hooks?

### ISSUE THREAD

**Issue by baron816** [SkinnyFatSumo/Visual-Portfolio-Platform#4]
I haven't seen hooks anywhere. You've upgraded to React 16.8, so you can use them. It's generally recommended not to refactor just to have them, but it's probably worthwhile for you to refactor a few components to use them just for practice.

**Comment by SkinnyFatSumo** [comment]
I wanted to focus more on using Redux in this project (not that they can't work together). But I'll be implementing hooks as a learning experience in my next project.
