### ISSUE TITLE
Binding arrow functions

### ISSUE THREAD

**Issue by baron816** [SkinnyFatSumo/Visual-Portfolio-Platform#6]
https://github.com/SkinnyFatSumo/Visual-Portfolio-Platform/blob/bc9411c771f14f9ff077db829331ca6f76affc59/visual_portfolio/react_frontend/src/components/photo/ContentRoot.js#L51

You shouldn't need to do this for class property arrow functions.

**Comment by SkinnyFatSumo** [comment]
True. However it's technically considered experimental syntax and not formally part of ES6. I'll probably go ahead and get rid of the binding just for a cleaner look though. Thanks!
